### ISSUE TITLE
weak sense in error

### ISSUE THREAD

**Issue by Fiv5** [alexnho/vscode-a-touch-of-lilac-theme#3]
Think you for nice theme! Here have a problem that I hard to sense  when the code had error.
Example : 
<img width="519" alt="屏幕快照 2019-12-14 下午8 24 24" src="https://user-images.githubusercontent.com/23014093/70848652-cb787280-1eaf-11ea-9093-0e8b3f518ff3.png">

**Comment by alexnho** [comment]
Hi @Fiv5 ,
I'll update the colors for errors, comments, warnings and info, in order to be more visible.
Here's how they will look after the code will be pushed.
<img width="348" alt="Screenshot 2020-03-16 at 19 42 24" src="https://user-images.githubusercontent.com/2949783/76785762-a81ad780-67be-11ea-9d51-946c12b7c117.png">

Thanks
