### ISSUE TITLE
Comment color is green

### ISSUE THREAD

**Issue by timstrasser** [alexnho/vscode-a-touch-of-lilac-theme#9]
In the provided screenshots the comments are gray, but for me comments get a green color. It this intended?

**Comment by alexandru-martin** [comment]
Hi @XENOTpro , not really intended, the comments color was indeed updated from gray to green because with the gray the comments were a bit hard to read. 
As for the screenshots, they are still the older ones and I need to update them, hope I can redo them in the next period and push them on the repo.

**Comment by alexnho** [comment]
Hi @XENOTpro , 
Not really intended, the comments color was indeed updated from gray to green because with the gray the comments were a bit hard to read.
As for the screenshots, they are still the older ones as I didn't found time to redo and push them to the repo. I'll try to do it in the next period.

**Comment by timstrasser** [comment]
Hi @alexnho, personally I find the gray much more pleasant. I think this green is just too vibrant for this background color. Maybe a softer green (like #55945F) would be a better choice.
Personally I changed the color back to this blueish gray: #8091B3
I think this color is much more pleasant to the eye. ;)

**Comment by alexnho** [comment]
Fair enough, I get why the green might be too visible for some people. :)
My idea with that vibrant green was that for the people that have the screen brightness on lower level (like me) will be also visible enough.
I promise that I'll look into changing it maybe to a `better` gray version (will give a try to the ones that you propose) in some future updates.

**Comment by timstrasser** [comment]
Sounds great! I absolutely love the theme, just this single color needed a rework. :)

**Comment by alexnho** [comment]
Thanks for the proposed blueish gray color @XENOTpro, I've gave it a try and liked it. :)
I've pushed the new comments styles to v1.2.1, based on the color I've also added some different shades to the comment to differentiate the elements inside them.
The comments look something like this:
![comment_styles](https://user-images.githubusercontent.com/2949783/78537666-8084c100-77f8-11ea-8103-d08e3280fdaf.jpg)

Regards
